apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: docker.io/amusarra/codeql-checkov-quickstart:latest # Immagine Docker da buildare
          ports:
            - containerPort: 5000
          securityContext:
            privileged: true # Container in modalità privilegiata!
          resources: # Limiti di risorse MANCANTI! VULNERABILITA'
            { } # Nessun limite specificato!