name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python  # Necessario per Checkov e il progetto Python di esempio
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: CodeQL Initialize
        uses: github/codeql-action/init@v2
        with:
          languages: python  # Specifica i linguaggi da analizzare

      - name: CodeQL Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v2

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: kubernetes,terraform,dockerfile # Specifica i framework da scansionare
          directory: . # Directory da scansionare (root del repository)
